import type { Config } from "tailwindcss";

const config: Config = {
  /** Funnel Step 3 vibe tiles — classes come from `data/funnel.ts` strings. */
  safelist: [
    "bg-pink-100",
    "ring-pink-400",
    "bg-purple-100",
    "ring-purple-400",
    "bg-yellow-100",
    "ring-yellow-400",
    "bg-red-100",
    "ring-red-400",
    "bg-green-100",
    "ring-green-400",
    "bg-amber-100",
    "ring-amber-400",
    "bg-sky-100",
    "ring-sky-400",
    "bg-blue-100",
    "ring-blue-400",
    "bg-orange-100",
    "ring-orange-400",
    "bg-teal-100",
    "ring-teal-400",
    "bg-indigo-100",
    "ring-indigo-400",
    "bg-fuchsia-100",
    "ring-fuchsia-400",
    "bg-rose-100",
    "ring-rose-400",
    "bg-violet-100",
    "ring-violet-400",
    "bg-emerald-100",
    "ring-emerald-400",
    "bg-emerald-600",
    "bg-rose-500",
    "bg-violet-500",
    "bg-sky-500",
    "bg-amber-500",
    "bg-emerald-500",
    "bg-fuchsia-500",
    "bg-orange-500",
    "bg-teal-500",
  ],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./data/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "rgb(var(--canvas) / <alpha-value>)",
        ink: "rgb(var(--ink) / <alpha-value>)",
        inkMuted: "rgb(var(--ink-muted) / <alpha-value>)",
        primary: "rgb(var(--primary) / <alpha-value>)",
        primarySoft: "rgb(var(--primary-soft) / <alpha-value>)",
        accentPink: "rgb(var(--accent-pink) / <alpha-value>)",
        accentOrange: "rgb(var(--accent-orange) / <alpha-value>)",
        accentGreen: "rgb(var(--accent-green) / <alpha-value>)",
        lavender: "rgb(var(--lavender) / <alpha-value>)",
        lavenderDeep: "rgb(var(--lavender-deep) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        display: ["var(--font-playfair)", "Georgia", "serif"],
      },
      boxShadow: {
        card: "0 10px 40px -12px rgba(181, 43, 42, 0.22), 0 4px 16px -8px rgba(0,0,0,0.12)",
        cardHover: "0 14px 48px -10px rgba(181, 43, 42, 0.28), 0 8px 24px -8px rgba(0,0,0,0.14)",
        pill: "0 4px 14px -4px rgba(181, 43, 42, 0.3)",
        fab: "0 12px 32px -8px rgba(181, 43, 42, 0.45)",
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(135deg, #B52B2A 0%, #D63B3A 100%)",
        "gradient-ring":
          "linear-gradient(135deg, #B52B2A 0%, #C93535 55%, #FF5A5A 100%)",
      },
    },
  },
  plugins: [],
};
export default config;
