import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth/require-admin";
import { getServiceSupabase } from "@/lib/supabase/admin";
import { parsePersonaPayload } from "@/lib/admin/persona-payload";
import { generatePersonaFromBrief } from "@/lib/admin/generate-persona";
import { generatePersonaPhoto } from "@/lib/images/generate-photo";
import { buildPersonaPhotoPrompt } from "@/lib/images/persona-photo-prompt";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
/** Grok call (~5-10s) + 1 avatar generation (~10-25s) easily exceeds the
 * default 10s serverless budget. We cap at 60s so a single persona has
 * room to land its image even on a slow HF Space cold-start. Multiple
 * personas are generated by the client looping this endpoint, so each
 * call stays under the per-invocation limit. */
export const maxDuration = 60;

type GenerateBody = {
  brief?: string;
  index?: number;
  total?: number;
  /** ids/names already produced in this batch — Grok is asked to pick
   * something different so a single batch yields varied personas. */
  exclude?: string[];
  /** When false, skip image generation entirely (text-only persona, fast
   * fallback when image backend is down or rate-limited). Default true. */
  with_avatar?: boolean;
};

/** Resolve a slug that doesn't collide with an existing chat_profiles row.
 * Suffixes -2, -3, ... up to -9 if needed; if all are taken we hash a
 * short random tail so the operator at least gets a usable id. */
async function resolveUniqueId(
  service: ReturnType<typeof getServiceSupabase>,
  proposed: string,
): Promise<string> {
  if (!service) return proposed;
  for (let i = 0; i < 10; i++) {
    const candidate = i === 0 ? proposed : `${proposed}-${i + 1}`;
    const { data } = await service
      .from("chat_profiles")
      .select("id")
      .eq("id", candidate)
      .maybeSingle();
    if (!data) return candidate;
  }
  const tail = Math.random().toString(36).slice(2, 6);
  return `${proposed}-${tail}`;
}

/** Default selfie scene for the auto-generated avatar — kept short and
 * generic so the persona's photo_style does the heavy lifting. */
const AVATAR_SCENE =
  "casual selfie thuis bij het raam, zacht daglicht, ze kijkt licht glimlachend in de camera";

export async function POST(req: Request) {
  const auth = await requireAdmin();
  if (!auth.ok) {
    return NextResponse.json({ error: auth.error }, { status: auth.status });
  }
  const service = getServiceSupabase();
  if (!service) {
    return NextResponse.json(
      { error: "SUPABASE_SERVICE_ROLE_KEY ontbreekt." },
      { status: 500 },
    );
  }

  let body: GenerateBody;
  try {
    body = (await req.json()) as GenerateBody;
  } catch {
    return NextResponse.json({ error: "Ongeldige JSON." }, { status: 400 });
  }

  const brief = (body.brief ?? "").trim();
  if (!brief || brief.length < 6) {
    return NextResponse.json(
      { error: "Brief is te kort — beschrijf het type persona in 1-3 zinnen." },
      { status: 400 },
    );
  }
  const index = Number.isFinite(body.index) ? Number(body.index) : 0;
  const total = Math.max(1, Math.min(20, Number(body.total) || 1));
  const exclude = Array.isArray(body.exclude) ? body.exclude.slice(0, 12).map(String) : [];
  const withAvatar = body.with_avatar !== false;

  // 1) Generate the persona text/JSON via Grok.
  const generated = await generatePersonaFromBrief({ brief, index, total, exclude });
  if (!generated.ok) {
    return NextResponse.json(
      { error: `Generatie faalde: ${generated.error}` },
      { status: 502 },
    );
  }

  // 2) Resolve a unique slug — Grok sometimes picks a name that already
  //    exists in our seed data; bumping the suffix is friendlier than
  //    surfacing a 409 to the operator mid-batch.
  const uniqueId = await resolveUniqueId(service, generated.persona.id);

  // 3) Optionally generate the avatar before the insert. Doing it in this
  //    order lets parsePersonaPayload enforce the avatar_url-required rule
  //    for create-mode without a placeholder hack.
  let avatarUrl = "";
  let avatarWarning: string | null = null;

  if (withAvatar) {
    const promptInput = {
      // Cast through unknown — buildPersonaPhotoPrompt expects ChatProfileRow
      // but only reads photo_style + age + city + id; the partial we pass
      // satisfies all of those.
      profile: {
        id: uniqueId,
        age: generated.persona.age,
        city: generated.persona.city,
        photo_style: generated.persona.photo_style,
      } as unknown as Parameters<typeof buildPersonaPhotoPrompt>[0]["profile"],
      scene: AVATAR_SCENE,
    };
    const { prompt, seed } = buildPersonaPhotoPrompt(promptInput);
    const photo = await generatePersonaPhoto({ prompt, seed });
    if (photo.ok) {
      const ext = /png/i.test(photo.mime) ? "png" : /jpe?g/i.test(photo.mime) ? "jpg" : "webp";
      const path = `admin-personas/${uniqueId}/avatar-${Date.now()}.${ext}`;
      const { error: upErr } = await service.storage
        .from("chat-images")
        .upload(path, photo.bytes, {
          contentType: photo.mime,
          cacheControl: "31536000",
          upsert: false,
        });
      if (upErr) {
        avatarWarning = `Foto gegenereerd maar upload faalde: ${upErr.message}`;
      } else {
        const { data } = service.storage.from("chat-images").getPublicUrl(path);
        if (data?.publicUrl) {
          avatarUrl = data.publicUrl;
        } else {
          avatarWarning = "Foto upload OK, maar kon public URL niet bepalen.";
        }
      }
    } else {
      avatarWarning = `Foto-generatie faalde (${photo.error}). Persona is opgeslagen, maar zonder avatar.`;
    }
  }

  // If we have no avatar (either because withAvatar=false or the backend
  // failed) we fall back to a 1x1 placeholder so the validator passes; the
  // admin can still open the persona and upload a real avatar manually.
  // We use a built-in pixel hosted in Supabase so it works offline; if no
  // placeholder env var is set we use a transparent data URL alternative
  // by leaving avatar_url empty and rejecting the create — but that
  // surfaces a worse UX, so we pick the placeholder path.
  if (!avatarUrl) {
    const placeholder = process.env.ADMIN_PERSONA_PLACEHOLDER_AVATAR_URL?.trim();
    if (placeholder && /^https?:\/\//i.test(placeholder)) {
      avatarUrl = placeholder;
    }
  }

  // 4) Build the validator payload from the generated persona + the
  //    resolved slug + the avatar URL we just produced.
  const payload = {
    id: uniqueId,
    display_name: generated.persona.display_name,
    age: generated.persona.age,
    city: generated.persona.city,
    bio: generated.persona.bio,
    occupation: generated.persona.occupation,
    backstory: generated.persona.backstory,
    looking_for: generated.persona.looking_for,
    avatar_url: avatarUrl,
    gallery_urls: [],
    interests: generated.persona.interests,
    vibe_tags: generated.persona.vibe_tags,
    funnel_intent_ids: generated.persona.funnel_intent_ids,
    filter_tags: generated.persona.filter_tags,
    status_variant: generated.persona.status_variant,
    status_label: generated.persona.status_label,
    last_active_label: "Active today",
    home_sort: 100,
    distance_km: 4,
    verified: true,
    online_now: generated.persona.status_variant === "online",
    is_archived: false,
    chat_style: generated.persona.chat_style,
    photo_style: generated.persona.photo_style,
    persona_meta: generated.persona.persona_meta,
  };

  const parsed = parsePersonaPayload(payload, { mode: "create" });
  if (!parsed.ok) {
    return NextResponse.json(
      { error: `Validatie faalde: ${parsed.error}`, generated: generated.persona },
      { status: 422 },
    );
  }

  const { error: insertError } = await service.from("chat_profiles").insert(parsed.row);
  if (insertError) {
    return NextResponse.json(
      { error: `Insert faalde: ${insertError.message}`, generated: generated.persona },
      { status: 500 },
    );
  }

  return NextResponse.json(
    {
      ok: true,
      persona: {
        id: parsed.row.id,
        display_name: parsed.row.display_name,
        age: parsed.row.age,
        city: parsed.row.city,
        occupation: parsed.row.occupation,
        avatar_url: parsed.row.avatar_url,
      },
      warning: avatarWarning,
    },
    { status: 201 },
  );
}
